spring:
 jpa:
  show-sql: true
 data:
  cassandra: 
   contact-points: 127.0.0.1
   port: 9042
   keyspace-name: medicationList
   password: cassandra
   username: cassandra
   schema-action: create-if-not-exists
   local-datacenter: datacenter1
             
             
logging:
 level:
  root:      
        
        
            
    
