server:  port: 9097
spring:
 application:
  name: medication-service
 jpa:
  show-sql: true
 data:
  cassandra: 
   contact-points: cassandra
   port: 9042
   keyspace-name: medicationList
   password: cassandra
   username: cassandra
   schema-action: create-if-not-exists
   local-datacenter: datacenter1
 
eureka.client.serviceUrl.defaultZone: http://${service-registry-container:service-registry-container}:8761/eureka
#eureka.instance.preferIpAddress: true            

client_id : kidclient
client_credential : kidsecret
check_authorization_url : http://${AUTH_HOSTNAME:localhost}:${AUTH_PORT:8080}/oauth/check_token
resources_id : ehealth


        
            
    
