spring:
 data:
  cassandra: 
   contact-points: 127.0.0.1
   port: 9042
   keyspace-name: appointment
   username: cassandra
   password: cassandra
   schema-action: create-if-not-exists
   local-datacenter: datacenter1